version: '3'
volumes:
  db:

services:

  mariadb:
   image: mariadb:10.4
   environment:
    MYSQL_DATABASE: "profiler"
    MYSQL_USER: profiler
    MYSQL_PASSWORD: password
    MYSQL_ROOT_PASSWORD: password
   volumes:
    - db:/var/lib/mysql
  
  web:
    build: ./src/
    depends_on:
      - mariadb
    links:
      - mariadb:db
    ports:
      - 80:80